---
name: Tailscale with features
version: 0.26.1.5
slug: tailscale
description: Zero config VPN for building secure networks
url: https://github.com/lmagyar/homeassistant-addon-tailscale
ingress: true
ingress_port: 0
ingress_stream: true
startup: services
panel_icon: mdi:vpn
arch:
  - aarch64
  - amd64
  - armv7
init: false
hassio_api: true
host_network: true
host_dbus: true
privileged:
  - NET_ADMIN
  - NET_RAW
  - SYS_ADMIN
devices:
  - /dev/net/tun
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
ports:
  41641/udp: null
options:
  accept_dns: true
  accept_routes: false
  advertise_exit_node: true
  advertise_connector: true
  advertise_routes:
    - local_subnets
  log_level: info
  login_server: "https://controlplane.tailscale.com"
  share_homeassistant: disabled
  share_on_port: 443
  snat_subnet_routes: true
  ssh: false
  stateful_filtering: false
  tags: []
  taildrive:
    addons: false
    addon_configs: false
    backup: false
    config: false
    media: false
    share: false
    ssl: false
  taildrop: true
  userspace_networking: true
schema:
  accept_dns: bool
  accept_routes: bool
  advertise_exit_node: bool
  advertise_connector: bool
  advertise_routes:
    - "match(^(?:local_subnets|(?:(?:25[0-5]|(?:2[0-4]|1\\d|[1-9]?)\\d)\\.){3}(?:25[0-5]|(?:2[0-4]|1\\d|[1-9]?)\\d)\\/(?:3[0-2]|[12]?\\d)|[a-fA-F\\d.:]+:[a-fA-F\\d.:]+\\/(?:12[0-8]|(?:1[01]|[1-9]?)\\d))$)"
  dscp: int(0,63)?
  exit_node: "match(^(?:(?:(?:25[0-5]|(?:2[0-4]|1\\d|[1-9]?)\\d)\\.){3}(?:25[0-5]|(?:2[0-4]|1\\d|[1-9]?)\\d)|[a-fA-F\\d.:]+:[a-fA-F\\d.:]+|[a-fA-F\\d]{8}(?:-[a-fA-F\\d]{4}){3}-[a-fA-F\\d]{12}|auto:any)$)?"
  lets_encrypt_certfile: str?
  lets_encrypt_keyfile: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  login_server: url
  share_homeassistant: list(disabled|serve|funnel)
  share_on_port: match(^(?:443|8443|10000)$)
  snat_subnet_routes: bool
  ssh: bool
  stateful_filtering: bool
  tags:
    - "match(^tag:[a-zA-Z][a-zA-Z0-9-]*$)"
  taildrive:
    addons: bool
    addon_configs: bool
    backup: bool
    config: bool
    media: bool
    share: bool
    ssl: bool
  taildrop: bool
  userspace_networking: bool
image: ghcr.io/lmagyar/{arch}-addon-tailscale
